[package]
name = "first-rust"
version = "0.1.0"
authors = ["Jeff Goodman <jeff@goodman.geek.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
